## CreaciÃ³n de Observables - throwError

Genera un Observable que (**directamente**) emite un error en la subscripciÃ³n.

```ts
const sec = rxjs.throwError("ðŸ‘¿");

sec.subscribe({
  error: (err) => console.log("ERROR", err) // ERROR ðŸ‘¿
})
```

Va a ser muy util para gestionar el flujo de errores cuando estemos combinando observables.
